[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/"
  to = "/es"
  status = 301

[[redirects]]
  from = "/portfolio"
  to = "/es/projects"
  status = 301

[[redirects]]
  from = "/planes"
  to = "/es/services"
  status = 301

[[redirects]]
  from = "/en/portfolioen"
  to = "/en/projects"
  status = 301

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
